# Generated by Django 6.0.5 on 2026-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='format',
            field=models.CharField(choices=[('CARTON_250', 'Carton 250 ml (×24)'), ('CARTON_500', 'Carton 500 ml (×16)'), ('CARTON_1L', 'Carton 1 L (×12)'), ('BIDON_5L', 'Bidon 5 L'), ('IBC_1000', 'IBC 1000 L'), ('VRAC', 'Vrac (litres)')], default='VRAC', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='liters',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_applied',
            field=models.BooleanField(default=False),
        ),
    ]
