# Generated by Django 6.0.5 on 2026-05-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='Link to product image')),
                ('material_quantity_per_unit', models.FloatField(help_text='e.g. 1.0 for 1L of Ethanol')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('base_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterial')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('packaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.packaging')),
            ],
        ),
    ]
