# Generated by Django 6.0.5 on 2026-05-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat ou coût de revient", max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_quantity_per_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.packaging'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente', max_digits=12),
        ),
    ]
