# Generated by Django 5.2.1 on 2026-05-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('L', 'Liters'), ('KG', 'Kilograms'), ('UNIT', 'Units')], default='UNIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0, help_text='Stock de produits finis'),
        ),
    ]
