# Generated by Django 6.0.5 on 2026-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_category_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alcohol_degree',
            field=models.IntegerField(default=0, help_text="Degré d'alcool (70, 96...)"),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_per_liter',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût de revient au litre', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de vente au litre', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_liters',
            field=models.FloatField(default=0, help_text='Stock de liquide fini (litres)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de vente', max_digits=12),
        ),
    ]
