# Generated by Django 6.0.5 on 2026-05-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(choices=[('SOCIETE', 'Société'), ('PARFUMERIE', 'Parfumerie'), ('PARTICULIER', 'Client Particulier'), ('GROSSISTE', 'Grossiste')], max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('rc', models.CharField(blank=True, help_text='Registre de Commerce', max_length=100, null=True)),
                ('nif', models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=100, null=True)),
                ('nis', models.CharField(blank=True, help_text="Numéro d'Identification Statistique", max_length=100, null=True)),
                ('ai', models.CharField(blank=True, help_text="Article d'Imposition", max_length=100, null=True)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.client')),
            ],
        ),
    ]
