# Generated by Django 6.0.5 on 2026-05-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(choices=[('L', 'Liters'), ('KG', 'Kilograms'), ('UNIT', 'Units')], max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOTTLE', 'Bottle'), ('CAP', 'Cap'), ('LABEL', 'Label'), ('CARTON', 'Carton')], max_length=20)),
                ('size', models.CharField(choices=[('1L', '1 Liter'), ('500ML', '500 ml'), ('250ML', '250 ml'), ('5L', '5 Liters'), ('OTHER', 'Other')], max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('type', 'size')},
            },
        ),
    ]
