# Generated by Django 6.0.5 on 2026-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_packaging_id_alter_rawmaterial_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packaging',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='packaging',
            name='alcohol_degree',
            field=models.IntegerField(default=0, help_text="Degré d'alcool (étiquettes). 0 = non applicable"),
        ),
        migrations.AddField(
            model_name='packaging',
            name='low_stock_threshold',
            field=models.IntegerField(default=0, help_text="Seuil d'alerte stock bas"),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='size',
            field=models.CharField(choices=[('250ML', '250 ml'), ('500ML', '500 ml'), ('1L', '1 Litre'), ('5L', '5 Litres'), ('PETIT', 'Petit carton'), ('GRAND', 'Grand carton'), ('NA', 'N/A'), ('OTHER', 'Other')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='type',
            field=models.CharField(choices=[('BOTTLE', 'Flacon'), ('CAP', 'Bouchon'), ('LABEL', 'Étiquette'), ('CARTON', 'Carton'), ('BIDON', 'Bidon')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='packaging',
            unique_together={('type', 'size', 'alcohol_degree')},
        ),
    ]
