"use client"

import React, { useEffect, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useRouter } from 'next/navigation'
import { API_BASE_URL } from '@/lib/api'
import { 
  Users, TrendingUp, AlertCircle, CheckCircle2, Phone, Building2,
  ArrowLeft, DollarSign, Plus, X, Download, ShoppingBag, Save,
  Search, Edit, Trash2, Filter, Truck, Calendar, UserPlus, Info, Check, Package, Layers, Camera, ArrowRight, LogOut
} from 'lucide-react'

export default function OwnerDashboard() {
  const [clients, setClients] = useState<any[]>([])
  const [orders, setOrders] = useState<any[]>([])
  const [products, setProducts] = useState<any[]>([])
  const [materials, setMaterials] = useState<any[]>([])
  const [activeTab, setActiveTab] = useState('overview')
  
  const [clientSearch, setClientSearch] = useState('')
  const [orderSearch, setOrderSearch] = useState('')

  const [showOrderModal, setShowOrderModal] = useState(false)
  const [showClientModal, setShowClientModal] = useState(false)
  const [showPaymentModal, setShowPaymentModal] = useState(false)
  const [showStockUpdateModal, setShowStockUpdateModal] = useState(false)
  const [showProductStockModal, setShowProductStockModal] = useState(false)
  const [showProductModal, setShowProductModal] = useState(false)
  const [showEditProductModal, setShowEditProductModal] = useState(false)
  
  const [notification, setNotification] = useState<{message: string, type: 'error' | 'success' | 'info' | 'confirm', onConfirm?: () => void} | null>(null)

  const showMsg = (message: string, type: 'error' | 'success' | 'info' | 'confirm' = 'info', onConfirm?: () => void) => {
    setNotification({ message, type, onConfirm });
    if (type !== 'confirm') {
      const duration = type === 'error' ? 8000 : 4000;
      setTimeout(() => setNotification(null), duration);
    }
  }

  const [selectedMaterial, setSelectedMaterial] = useState<any>(null)
  const [selectedProduct, setSelectedProduct] = useState<any>(null)
  const [stockAddAmount, setStockAddAddAmount] = useState<any>(1)

  const [wizardStep, setWizardStep] = useState(1)
  const [clientSearchQuery, setClientSearchQuery] = useState('')
  
  const [newOrder, setNewOrder] = useState({ client: '', items: [{ product: '', quantity: 1, price_at_sale: 0 }], status: 'PENDING', expected_delivery: '' })
  const [newClient, setNewClient] = useState({ name: '', domain: 'SOCIETE', address: '', phone: '', nif: '', rc: '' })
  const [newPayment, setNewPayment] = useState({ client: '', amount: 1, note: '' })
  
  const [newProduct, setNewProduct] = useState({ name: '', description: '', image: null, purchase_price: 1, unit_price: 1, quantity: 0, unit: 'UNIT' })
  const [editProductData, setEditProductData] = useState({ id: '', name: '', description: '', image: null, purchase_price: 1, unit_price: 1, quantity: 0, unit: 'UNIT' })

  const [isLoading, setIsLoading] = useState(true)
  const router = useRouter()

  const autoGenerateDescription = (name: string) => {
    if (!name) return "";
    return `${name} est un produit d'exception développé par le Laboratoire Akrabiolab. Spécialement conçu pour offrir une protection antiseptique maximale, ce produit allie haute qualité scientifique et efficacité prouvée. Idéal pour un usage professionnel ou domestique, il garantit une hygiène irréprochable au meilleur prix du marché.`;
  }

  const handleNameChange = (e: any, isEdit = false) => {
    const name = e.target.value;
    const desc = autoGenerateDescription(name);
    if (isEdit) {
        setEditProductData({ ...editProductData, name, description: desc });
    } else {
        setNewProduct({ ...newProduct, name, description: desc });
    }
  }

  const fetchData = async () => {
    const token = localStorage.getItem('akrabiolab_access');
    if (!token) {
      router.push('/admin-login');
      return;
    }

    try {
      const headers = { 'Authorization': `Bearer ${token}` };
      const [cRes, oRes, pRes, mRes] = await Promise.all([
        fetch(`${API_BASE_URL}/api/finance/clients/`, { headers }),
        fetch(`${API_BASE_URL}/api/orders/list/`, { headers }),
        fetch(`${API_BASE_URL}/api/products/items/`, { headers }),
        fetch(`${API_BASE_URL}/api/inventory/materials/`, { headers })
      ]);

      if (cRes.status === 401) {
        localStorage.removeItem('akrabiolab_access');
        router.push('/admin-login');
        return;
      }

      setClients(await cRes.json());
      setOrders(await oRes.json());
      setProducts(await pRes.json());
      setMaterials(await mRes.json());
    } catch(err) { 
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { 
    const token = localStorage.getItem('akrabiolab_access');
    if (!token) {
      router.push('/admin-login');
    } else {
      fetchData();
    }
  }, [])

  if (isLoading) {
    return (
      <div className="min-h-screen bg-[#0f172a] flex items-center justify-center">
        <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: "linear" }} className="w-16 h-16 border-4 border-emerald-500 border-t-transparent rounded-full" />
      </div>
    )
  }

  const handleLogout = () => {
    localStorage.removeItem('akrabiolab_access');
    localStorage.removeItem('akrabiolab_refresh');
    localStorage.removeItem('akrabiolab_user');
    router.push('/admin-login');
  }

  const handleDeliverOrder = async (orderId: string | number) => {
    const token = localStorage.getItem('akrabiolab_access');
    try {
      const res = await fetch(`${API_BASE_URL}/api/orders/list/${orderId}/`, {
          method: 'PATCH',
          headers: { 
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify({ status: 'DELIVERED' })
      });
      if (res.ok) {
          await fetchData();
          window.open(`${API_BASE_URL}/api/orders/download-invoice/${orderId}/`, '_blank');
          setTimeout(() => window.open(`${API_BASE_URL}/api/orders/download-bl/${orderId}/`, '_blank'), 500);
      }
    } catch (err) { console.error("Deliver error:", err) }
  }

  const handleUpdateStock = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem('akrabiolab_access');
    try {
      const newQty = (selectedMaterial as any).quantity + parseFloat(stockAddAmount as any);
      const res = await fetch(`${API_BASE_URL}/api/inventory/materials/${(selectedMaterial as any).id}/`, {
          method: 'PATCH',
          headers: { 
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify({ quantity: newQty })
      });
      if (res.ok) { 
        setShowStockUpdateModal(false); 
        await fetchData(); 
      }
    } catch (err) { console.error("Stock update error:", err) }
  }

  const handleUpdateProductStock = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem('akrabiolab_access');
    try {
      const newQty = parseFloat((selectedProduct as any).quantity) + parseFloat(stockAddAmount as any);
      const res = await fetch(`${API_BASE_URL}/api/products/items/${(selectedProduct as any).id}/`, {
          method: 'PATCH',
          headers: { 
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify({ quantity: newQty })
      });
      if (res.ok) { 
        setShowProductStockModal(false); 
        await fetchData(); 
      }
    } catch (err) { console.error("Product stock update error:", err) }
  }

  const handleAddProduct = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem('akrabiolab_access');
    const formData = new FormData();
    formData.append('name', newProduct.name);
    formData.append('description', newProduct.description);
    formData.append('purchase_price', newProduct.purchase_price.toString());
    formData.append('unit_price', newProduct.unit_price.toString());
    formData.append('quantity', newProduct.quantity.toString());
    formData.append('unit', newProduct.unit);
    if (newProduct.image) formData.append('image', newProduct.image);

    try {
      const res = await fetch(`${API_BASE_URL}/api/products/items/`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}` },
        body: formData
      });
      if (res.ok) {
        setShowProductModal(false);
        setNewProduct({ name: '', description: '', image: null, purchase_price: 1, unit_price: 1, quantity: 0, unit: 'UNIT' });
        await fetchData();
      }
    } catch (err) { console.error(err) }
  }

  const handleUpdateProduct = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem('akrabiolab_access');
    const formData = new FormData();
    formData.append('name', editProductData.name);
    formData.append('description', editProductData.description);
    formData.append('purchase_price', editProductData.purchase_price.toString());
    formData.append('unit_price', editProductData.unit_price.toString());
    formData.append('quantity', editProductData.quantity.toString());
    formData.append('unit', editProductData.unit);
    if ((editProductData.image as any) instanceof File) {
        formData.append('image', editProductData.image as any);
    }

    try {
      const res = await fetch(`${API_BASE_URL}/api/products/items/${editProductData.id}/`, {
          method: 'PATCH',
          headers: { 'Authorization': `Bearer ${token}` },
          body: formData
      });
      if (res.ok) { 
        setShowEditProductModal(false); 
        await fetchData(); 
      }
    } catch (err) { console.error("Update product error:", err) }
  }

  const handleDeleteProduct = async (productId: string | number) => {
    if (confirm("Supprimer définitivement ce produit du catalogue ?")) {
      const token = localStorage.getItem('akrabiolab_access');
      try {
        const res = await fetch(`${API_BASE_URL}/api/products/items/${productId}/`, { 
          method: 'DELETE',
          headers: { 'Authorization': `Bearer ${token}` }
        });
        if (res.ok) await fetchData();
      } catch (err) { console.error(err) }
    }
  }

  const handleFinalizeOrder = async (e: any, ignoreStock = false) => {
    if (e) e.preventDefault();
    const token = localStorage.getItem('akrabiolab_access');
    try {
      const res = await fetch(`${API_BASE_URL}/api/orders/list/`, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({ ...newOrder, ignore_stock: ignoreStock })
      });
      
      if (res.ok) {
        setShowOrderModal(false);
        setWizardStep(1);
        setClientSearchQuery('');
        setNewOrder({ client: '', items: [{ product: '', quantity: 1, price_at_sale: 0 }], status: 'PENDING', expected_delivery: '' });
        await fetchData();
        setActiveTab('pending');
        showMsg("Commande lancée avec succès !", "success");
      } else {
        const errorData = await res.json();
        if (errorData.type === "STOCK_LOW") {
          showMsg(
            errorData.items.join("\n") + "\n\nVoulez-vous quand même forcer cette commande ?", 
            "confirm",
            () => handleFinalizeOrder(null, true)
          );
        } else if (errorData.items && Array.isArray(errorData.items)) {
          showMsg(errorData.items.join("\n"), "error");
        } else if (errorData.detail) {
          showMsg(errorData.detail, "error");
        } else {
          showMsg("Erreur lors de la création de la commande", "error");
        }
      }
    } catch (err) { 
      console.error("Order creation error:", err);
      showMsg("Erreur de connexion au serveur", "error");
    }
  }

  const handleAddClient = async (e: React.FormEvent) => {
    e.preventDefault()
    const token = localStorage.getItem('akrabiolab_access');
    try {
      const res = await fetch(`${API_BASE_URL}/api/finance/clients/`, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(newClient)
      })
      if (res.ok) {
        const clientData = await res.json();
        await fetchData();
        setShowClientModal(false);
        if (showOrderModal) { 
          setNewOrder({...newOrder, client: clientData.id});
          setWizardStep(2); 
        }
      }
    } catch (err) { console.error("Client creation error:", err) }
  }

  const handleDeleteClient = async (clientId: string | number) => {
    if (confirm("Supprimer définitivement ce client ? Toutes ses données financières seront effacées.")) {
      const token = localStorage.getItem('akrabiolab_access');
      try {
        const res = await fetch(`${API_BASE_URL}/api/finance/clients/${clientId}/`, { 
          method: 'DELETE',
          headers: { 'Authorization': `Bearer ${token}` }
        });
        if (res.ok) await fetchData();
      } catch (err) { console.error(err) }
    }
  }

  const handleAddPayment = async (e: React.FormEvent) => {
    e.preventDefault()
    const token = localStorage.getItem('akrabiolab_access');
    const client = clients.find((c: any) => c.id === newPayment.client);
    const balance = client ? parseFloat(client.total_debt) - parseFloat(client.total_paid) : 0;

    if (parseFloat(newPayment.amount as any) > balance) {
        showMsg(`Impossible : L'encaissement (${newPayment.amount} DA) est plus grand que la dette (${balance} DA).`, 'error');
        return;
    }

    try {
      const res = await fetch(`${API_BASE_URL}/api/finance/payments/`, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(newPayment)
      })
      const data = await res.json();
      if (res.ok) { 
        setShowPaymentModal(false); 
        showMsg("Paiement enregistré avec succès", "success");
        await fetchData(); 
      } else {
        showMsg(data.detail || "Erreur lors de l'enregistrement du paiement", "error");
      }
    } catch (err) { 
        console.error("Payment error:", err);
        showMsg("Erreur de connexion au serveur", "error");
    }
  }

  const handleDeleteOrder = async (order: any) => {
    let message = `Voulez-vous supprimer cette commande ?`;
    if (order.status === 'DELIVERED') {
        const total = parseFloat(order.total_amount_ttc).toLocaleString();
        message = `ATTENTION: Cette commande est déjà LIVRÉE. Si vous la supprimez, la dette du client (${order.client_name}) diminuera de ${total} DA.\n\nÊtes-vous sûr de vouloir continuer ?`;
    }

    if (confirm(message)) {
      const token = localStorage.getItem('akrabiolab_access');
      try {
        const res = await fetch(`${API_BASE_URL}/api/orders/list/${order.id}/`, { 
          method: 'DELETE',
          headers: { 'Authorization': `Bearer ${token}` }
        });
        if (res.ok) await fetchData();
      } catch (err) { console.error(err) }
    }
  }

  const handleClientWizard = (e: React.FormEvent) => {
    e.preventDefault();
    const found = (clients as any[]).find(c => c.name.toLowerCase() === clientSearchQuery.toLowerCase());
    if (found) {
        setNewOrder({...newOrder, client: found.id});
        setWizardStep(2);
    } else {
        if(confirm("Client non enregistré. Créer maintenant ?")) {
            setNewClient({...newClient, name: clientSearchQuery});
            setShowOrderModal(true); 
            setShowClientModal(true);
        }
    }
  }

  const calculateWizardTotal = () => {
    const totalHT = newOrder.items.reduce((acc: number, item: any) => acc + (parseFloat(item.quantity || 0) * parseFloat(item.price_at_sale || 0)), 0);
    const totalTTC = totalHT * 1.19;
    return { ht: totalHT, ttc: totalTTC };
  }

  const pendingOrders = (orders as any[]).filter(o => o.status === 'PENDING').filter(o => o.client_name.toLowerCase().includes(orderSearch.toLowerCase()))
  const historyOrders = (orders as any[]).filter(o => o.status === 'DELIVERED').filter(o => o.client_name.toLowerCase().includes(orderSearch.toLowerCase()))
  const filteredClients = (clients as any[]).filter(c => c.name.toLowerCase().includes(clientSearch.toLowerCase()))

  const totalPaid = (clients as any[]).reduce((acc: number, c: any) => acc + (parseFloat(c.total_paid) || 0), 0)
  const currentBalance = (clients as any[]).reduce((acc: number, c: any) => acc + Math.max(0, (parseFloat(c.total_debt || 0) - parseFloat(c.total_paid || 0))), 0)

  const renderProductImage = (img: string | null) => {
    if (!img) return '/images/akrabilab-logo.png';
    if (img.startsWith('http')) return img;
    return `${API_BASE_URL}${img}`;
  }

  return (
    <main className="min-h-screen bg-[#f1f5f9] font-sans text-slate-900 pb-20 selection:bg-emerald-100 selection:text-emerald-900">
      <div className="bg-white/80 backdrop-blur-xl border-b border-slate-200 px-4 md:px-8 py-5 sticky top-0 z-50 flex flex-col md:flex-row items-center justify-between shadow-sm gap-4">
        <div className="flex items-center justify-between w-full md:w-auto gap-4 md:gap-8">
          <a href="/" className="text-slate-400 hover:text-emerald-600 font-bold text-xs md:text-sm flex items-center gap-1 transition-colors"><ArrowLeft size={16}/> Site Public</a>
          <div className="flex items-center gap-2 md:gap-4">
            <img src="/images/akrabilab-logo.png" alt="Logo" className="h-8 md:h-12 w-auto" />
            <div className="h-6 md:h-8 w-px bg-slate-200"></div>
            <h1 className="text-sm md:text-xl font-black uppercase tracking-tighter truncate">Akrabiolab <span className="text-emerald-600 hidden xs:inline">Pro-Panel</span></h1>
          </div>
        </div>
        <div className="flex items-center gap-3 md:gap-4 w-full md:w-auto">
          <button onClick={handleLogout} className="p-3 md:p-4 bg-slate-100 text-slate-500 rounded-xl md:rounded-2xl hover:bg-rose-50 hover:text-rose-600 transition-all flex-shrink-0"><LogOut size={20}/></button>
          <button onClick={() => { setWizardStep(1); setShowOrderModal(true); }} className="flex-1 md:flex-none px-4 md:px-8 py-3 md:py-4 bg-orange-500 text-white font-black rounded-xl md:rounded-2xl hover:bg-orange-600 hover:scale-[1.02] active:scale-[0.98] shadow-lg shadow-orange-200 transition-all flex items-center justify-center gap-2 text-xs md:text-base"><Truck size={20}/> <span className="hidden sm:inline">Nouvelle Commande</span><span className="sm:hidden">Commander</span></button>
        </div>
      </div>

      <div className="max-w-[1400px] mx-auto p-4 md:p-10">
        <div className="flex gap-2 md:gap-4 mb-8 md:mb-12 overflow-x-auto pb-4 no-scrollbar -mx-4 px-4 md:mx-0 md:px-0">
            <TabButton active={activeTab === 'overview'} onClick={() => setActiveTab('overview')} label="Gains" icon={<TrendingUp size={18}/>} />
            <TabButton active={activeTab === 'stock'} onClick={() => setActiveTab('stock')} label="Stock" icon={<Layers size={18}/>} />
            <TabButton active={activeTab === 'pending'} onClick={() => setActiveTab('pending')} label={`Production (${pendingOrders.length})`} icon={<Truck size={18}/>} />
            <TabButton active={activeTab === 'history'} onClick={() => setActiveTab('history')} label="Historique" icon={<ShoppingBag size={18}/>} />
            <TabButton active={activeTab === 'products'} onClick={() => setActiveTab('products')} label="Catalogue" icon={<Package size={18}/>} />
            <TabButton active={activeTab === 'clients'} onClick={() => setActiveTab('clients')} label="Clients" icon={<Users size={18}/>} />
        </div>

        <AnimatePresence mode="wait">
        {activeTab === 'overview' && (
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="space-y-6 md:space-y-12">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-8">
                    <InsightCard label="Créances Dehors" value={currentBalance.toLocaleString()} unit="DA" status="danger" icon={<AlertCircle />} desc="Ventes livrées non payées" />
                    <InsightCard label="Encaissement Réel" value={totalPaid.toLocaleString()} unit="DA" status="success" icon={<CheckCircle2 />} desc="Cash en caisse" />
                    <InsightCard label="Gains Brut" value={(orders as any[]).reduce((acc: number, o: any) => acc + parseFloat(o.pure_gain), 0).toLocaleString()} unit="DA" status="info" icon={<TrendingUp />} desc="Bénéfice Réel" />
                </div>
                <div className="bg-white p-6 md:p-12 rounded-[2rem] md:rounded-[3.5rem] shadow-xl border border-slate-100 flex flex-col md:flex-row items-center justify-between relative overflow-hidden gap-8">
                    <div className="relative z-10 text-center md:text-left">
                        <h3 className="text-xl md:text-3xl font-black mb-4 flex items-center justify-center md:justify-start gap-3"><TrendingUp className="text-emerald-600"/> Analyse de l'Activité</h3>
                        <p className="text-slate-500 max-w-2xl text-sm md:text-lg font-medium leading-relaxed">Bienvenue sur votre tableau de bord professionnel. Tous vos indicateurs financiers sont calculés en temps réel pour une gestion optimale de votre laboratoire.</p>
                    </div>
                    <img src="/images/akrabilab-logo.png" alt="Logo" className="h-24 md:h-48 opacity-10 absolute -right-4 -bottom-4 md:-right-10 md:-bottom-10 rotate-12" />
                </div>
            </motion.div>
        )}

        {activeTab === 'stock' && (
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="space-y-6 md:space-y-12">
                <div className="bg-white rounded-[2rem] md:rounded-[3.5rem] border border-slate-200 shadow-xl overflow-hidden">
                    <div className="p-6 md:p-10 border-b border-slate-100 flex items-center justify-between bg-emerald-50/30">
                        <h3 className="text-lg md:text-2xl font-black uppercase tracking-tighter text-emerald-900">Produits Finis</h3>
                        <Package className="text-emerald-600" size={24} />
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-8 p-6 md:p-10">
                        {(products as any[]).map((prod: any) => (
                            <div key={prod.id} className="p-6 md:p-8 bg-slate-50 rounded-[2rem] md:rounded-[2.5rem] border border-slate-100 group hover:bg-white hover:shadow-2xl transition-all relative overflow-hidden">
                                <div className="flex justify-between items-start mb-4 md:mb-6">
                                    <div className="w-10 h-10 md:w-14 md:h-14 bg-orange-100 text-orange-600 rounded-xl md:rounded-2xl flex items-center justify-center"><Package size={20}/></div>
                                    <button onClick={() => { setSelectedProduct(prod); setStockAddAddAmount(1); setShowProductStockModal(true); }} className="p-2 md:p-3 bg-emerald-600 text-white rounded-lg md:rounded-xl shadow-lg md:opacity-0 group-hover:opacity-100 transform translate-y-0 md:translate-y-2 md:group-hover:translate-y-0 transition-all"><Plus size={16}/></button>
                                </div>
                                <h4 className="text-base md:text-lg font-black text-slate-800 leading-tight mb-1 md:mb-2">{prod.name}</h4>
                                <div className="mt-2 flex items-end justify-between border-t border-slate-100 pt-4 md:pt-6">
                                    <div>
                                        <p className="text-[9px] md:text-[10px] font-black uppercase text-slate-400 mb-1">En Stock</p>
                                        <p className={`text-xl md:text-3xl font-black ${prod.quantity < 5 ? 'text-rose-600' : 'text-emerald-600'}`}>{prod.quantity} <small className="text-[10px] md:text-xs font-bold opacity-50 uppercase">{prod.unit}</small></p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="bg-white rounded-[2rem] md:rounded-[3.5rem] border border-slate-200 shadow-xl overflow-hidden">
                    <div className="p-6 md:p-10 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
                        <h3 className="text-lg md:text-2xl font-black uppercase tracking-tighter text-slate-800">Matières Premières</h3>
                        <Layers className="text-slate-400" size={24} />
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-8 p-6 md:p-10">
                        {(materials as any[]).map((mat: any) => (
                            <div key={mat.id} className="p-6 md:p-8 bg-slate-50 rounded-[2rem] md:rounded-[2.5rem] border border-slate-100 group hover:bg-white hover:shadow-2xl transition-all">
                                <div className="flex justify-between items-start mb-4 md:mb-6">
                                    <div className="w-10 h-10 md:w-14 md:h-14 bg-emerald-100 text-emerald-600 rounded-xl md:rounded-2xl flex items-center justify-center"><Layers size={20}/></div>
                                    <button onClick={() => { setSelectedMaterial(mat); setStockAddAddAmount(1); setShowStockUpdateModal(true); }} className="p-2 md:p-3 bg-emerald-600 text-white rounded-lg md:rounded-xl shadow-lg md:opacity-0 group-hover:opacity-100 transform translate-y-0 md:translate-y-2 md:group-hover:translate-y-0 transition-all"><Plus size={16}/></button>
                                </div>
                                <h4 className="text-base md:text-lg font-black text-slate-800 leading-tight mb-1 md:mb-2">{mat.name}</h4>
                                <div className="mt-2 flex items-end justify-between border-t border-slate-100 pt-4 md:pt-6">
                                    <div>
                                        <p className="text-[9px] md:text-[10px] font-black uppercase text-slate-400 mb-1">Disponible</p>
                                        <p className={`text-xl md:text-3xl font-black ${mat.quantity < 10 ? 'text-rose-600' : 'text-slate-900'}`}>{mat.quantity} <small className="text-[10px] md:text-xs font-bold opacity-50 uppercase">{mat.unit}</small></p>
                                    </div>
                                    <div className="text-right">
                                        <p className="text-[9px] md:text-[10px] font-black uppercase text-slate-400 mb-1">Coût U</p>
                                        <p className="text-xs md:text-sm font-bold text-slate-500">{mat.unit_cost} DA</p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </motion.div>
        )}

        {activeTab === 'pending' && (
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="bg-white rounded-[2rem] md:rounded-[3.5rem] border border-slate-200 shadow-xl overflow-hidden">
                <div className="p-6 md:p-10 border-b border-slate-100 flex items-center justify-between text-lg md:text-2xl font-black uppercase tracking-tighter">Production</div>
                <div className="overflow-x-auto">
                    <table className="w-full text-left min-w-[800px] md:min-w-0">
                        <thead className="bg-slate-50 text-[10px] md:text-[11px] uppercase font-black text-slate-400"><tr><th className="px-6 md:px-10 py-4 md:py-6">Client</th><th className="px-6 md:px-10 py-4 md:py-6">Composition</th><th className="px-6 md:px-10 py-4 md:py-6">Total TTC</th><th className="px-6 md:px-10 py-4 md:py-6 text-center">Action</th></tr></thead>
                        <tbody className="divide-y divide-slate-100">
                            {(pendingOrders as any[]).map((order: any) => (
                                <tr key={order.id} className="hover:bg-emerald-50/30 transition-colors">
                                    <td className="px-6 md:px-10 py-6 md:py-8 font-black text-base md:text-lg">{order.client_name}</td>
                                    <td className="px-6 md:px-10 py-6 md:py-8">
                                        <div className="flex flex-wrap gap-1 md:gap-2">{(order.items as any[]).map((item: any, idx: number) => (
                                            <div key={idx} className="bg-emerald-100/50 text-emerald-800 px-3 md:px-4 py-1 md:py-1.5 rounded-lg md:rounded-xl text-[9px] md:text-[11px] font-black border border-emerald-100">{item.product_name} x{item.quantity}</div>
                                        ))}</div>
                                    </td>
                                    <td className="px-6 md:px-10 py-6 md:py-8 font-black text-slate-900 text-base md:text-lg">{parseFloat(order.total_amount_ttc).toLocaleString()} DA</td>
                                    <td className="px-6 md:px-10 py-6 md:py-8 text-center">
                                        <div className="flex gap-2 md:gap-3 justify-center">
                                            <button onClick={() => handleDeliverOrder(order.id)} className="px-4 md:px-6 py-2 md:py-3 bg-emerald-600 text-white rounded-xl md:rounded-2xl text-[9px] md:text-[11px] font-black hover:bg-emerald-700 flex items-center gap-1 md:gap-2 shadow-lg shadow-emerald-100 transition-all active:scale-95 uppercase tracking-widest"><Check size={14}/> LIVRER</button>
                                            <button onClick={() => handleDeleteOrder(order)} className="p-2 md:p-3 bg-rose-50 text-rose-600 rounded-lg md:rounded-xl hover:bg-rose-600 hover:text-white transition-all"><Trash2 size={18}/></button>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </motion.div>
        )}

        {activeTab === 'history' && (
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="bg-white rounded-[2rem] md:rounded-[3.5rem] border border-slate-200 shadow-xl overflow-hidden">
                <div className="p-6 md:p-10 border-b border-slate-100 flex items-center justify-between text-lg md:text-2xl font-black uppercase tracking-tighter">Historique des Ventes</div>
                <div className="overflow-x-auto">
                    <table className="w-full text-left min-w-[800px] md:min-w-0">
                        <thead className="bg-slate-50 text-[10px] md:text-[11px] uppercase font-black text-slate-400"><tr><th className="px-6 md:px-10 py-4 md:py-6">Date</th><th className="px-6 md:px-10 py-4 md:py-6">Client</th><th className="px-6 md:px-10 py-4 md:py-6">Montant TTC</th><th className="px-6 md:px-10 py-4 md:py-6 text-center">Documents</th><th className="px-6 md:px-10 py-4 md:py-6 text-center">Action</th></tr></thead>
                        <tbody className="divide-y divide-slate-100">
                            {(historyOrders as any[]).map((order: any) => (
                                <tr key={order.id} className="hover:bg-slate-50/50 transition-colors">
                                    <td className="px-6 md:px-10 py-6 md:py-8 text-xs md:text-sm font-bold text-slate-400">{new Date(order.created_at).toLocaleDateString()}</td>
                                    <td className="px-6 md:px-10 py-6 md:py-8 font-black text-base md:text-lg">{order.client_name}</td>
                                    <td className="px-6 md:px-10 py-6 md:py-8 font-black text-emerald-700 text-base md:text-lg">{parseFloat(order.total_amount_ttc).toLocaleString()} DA</td>
                                    <td className="px-6 md:px-10 py-6 md:py-8 text-center">
                                        <div className="flex justify-center gap-2 md:gap-3">
                                            <a href={`${API_BASE_URL}/api/orders/download-invoice/${order.id}/`} target="_blank" className="p-2 md:p-3 bg-slate-900 text-white rounded-lg md:rounded-xl shadow-lg hover:scale-105 transition-all" title="Facture"><Download size={16}/></a>
                                            <a href={`${API_BASE_URL}/api/orders/download-bl/${order.id}/`} target="_blank" className="p-2 md:p-3 bg-emerald-600 text-white rounded-lg md:rounded-xl shadow-lg hover:scale-105 transition-all" title="Bon de Livraison"><Truck size={16}/></a>
                                        </div>
                                    </td>
                                    <td className="px-6 md:px-10 py-6 md:py-8 text-center"><button onClick={() => handleDeleteOrder(order)} className="p-2 md:p-3 bg-rose-50 text-rose-600 rounded-lg md:rounded-xl hover:bg-rose-600 hover:text-white transition-all"><Trash2 size={16}/></button></td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </motion.div>
        )}

        {activeTab === 'products' && (
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="bg-white rounded-[2rem] md:rounded-[3.5rem] border border-slate-200 shadow-xl overflow-hidden">
                <div className="p-6 md:p-10 border-b border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-6">
                    <h3 className="text-lg md:text-2xl font-black uppercase tracking-tighter">Catalogue Produits</h3>
                    <button onClick={() => setShowProductModal(true)} className="w-full sm:w-auto px-6 md:px-8 py-3 md:py-4 bg-orange-500 text-white font-black rounded-xl md:rounded-2xl shadow-xl hover:bg-orange-600 hover:scale-[1.02] transition-all flex items-center justify-center gap-2 text-xs md:text-base"><Plus size={20}/> Nouveau Produit</button>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8 p-6 md:p-10">
                    {(products as any[]).map((product: any) => (
                        <div key={product.id} className="group bg-slate-50 rounded-[2rem] md:rounded-[3rem] overflow-hidden border border-slate-100 hover:bg-white hover:shadow-2xl transition-all relative">
                            <div className="h-40 md:h-48 overflow-hidden relative">
                                <img src={renderProductImage(product.image)} alt={product.name} className={`w-full h-full ${product.image ? 'object-cover' : 'object-contain p-8 opacity-20'} group-hover:scale-110 transition-transform duration-500`} />
                                <div className="absolute top-4 right-4 flex gap-2">
                                    <button onClick={() => { 
                                        setEditProductData({
                                            id: product.id,
                                            name: product.name,
                                            description: product.description,
                                            purchase_price: product.purchase_price,
                                            unit_price: product.unit_price,
                                            image: product.image,
                                            quantity: product.quantity,
                                            unit: product.unit
                                        });
                                        setShowEditProductModal(true); 
                                    }} className="p-2 md:p-3 bg-white/90 backdrop-blur text-emerald-600 rounded-xl md:rounded-2xl shadow-xl hover:bg-emerald-600 hover:text-white transition-all"><Edit size={16}/></button>
                                    <button onClick={() => handleDeleteProduct(product.id)} className="p-2 md:p-3 bg-white/90 backdrop-blur text-rose-600 rounded-xl md:rounded-2xl shadow-xl hover:bg-rose-600 hover:text-white transition-all"><Trash2 size={16}/></button>
                                </div>
                            </div>
                            <div className="p-6 md:p-8">
                                <div className="flex justify-between items-start mb-4">
                                    <div>
                                        <h4 className="text-base md:text-xl font-black text-slate-800 leading-tight">{product.name}</h4>
                                    </div>
                                </div>
                                <div className="flex items-center justify-between mt-4 md:mt-6 pt-4 md:pt-6 border-t border-slate-200/50">
                                    <div>
                                        <p className="text-[9px] md:text-[10px] font-black uppercase text-slate-400">Prix Public</p>
                                        <p className="text-lg md:text-2xl font-black text-slate-900">{parseFloat(product.unit_price).toLocaleString()} <small className="text-[10px] md:text-xs font-medium opacity-50">DA</small></p>
                                    </div>
                                    <div className="text-right">
                                        <p className="text-[9px] md:text-[10px] font-black uppercase text-slate-400">Coût</p>
                                        <p className="text-xs md:text-sm font-bold text-orange-500">{parseFloat(product.purchase_price).toLocaleString()} DA</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </motion.div>
        )}

        {activeTab === 'clients' && (
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="bg-white rounded-[2rem] md:rounded-[3.5rem] border border-slate-200 shadow-xl overflow-hidden">
                <div className="p-6 md:p-10 border-b border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-6">
                    <h3 className="text-lg md:text-2xl font-black uppercase tracking-tighter">Portefeuille Clients</h3>
                    <button className="w-full sm:w-auto px-6 md:px-8 py-3 md:py-4 bg-emerald-600 text-white font-black rounded-xl md:rounded-2xl shadow-xl hover:bg-emerald-700 transition-all flex items-center justify-center gap-2 text-xs md:text-base" onClick={() => { setNewClient({name:'', domain:'SOCIETE', address:'', phone:'', nif:'', rc:''}); setShowClientModal(true); }}><UserPlus size={20}/> Nouveau Client</button>
                </div>
                <div className="overflow-x-auto">
                    <table className="w-full text-left min-w-[600px] md:min-w-0">
                        <thead className="bg-slate-50 text-[10px] md:text-[11px] uppercase font-black text-slate-400"><tr><th className="px-6 md:px-10 py-4 md:py-6">Client</th><th className="px-6 md:px-10 py-4 md:py-6">Dette Livrée</th><th className="px-6 md:px-10 py-4 md:py-6 text-center">Action</th></tr></thead>
                        <tbody className="divide-y divide-slate-100">
                            {(filteredClients as any[]).map((client: any) => (
                                <tr key={client.id} className="hover:bg-slate-50/50 transition-colors">
                                    <td className="px-6 md:px-10 py-6 md:py-8"><div className="font-black text-slate-800 text-base md:text-lg">{client.name}</div><div className="text-[10px] md:text-xs text-slate-400 font-bold">{client.phone}</div></td>
                                    <td className="px-6 md:px-10 py-6 md:py-8 font-black text-rose-600 text-lg md:text-xl">{Math.max(0, (parseFloat(client.total_debt) - parseFloat(client.total_paid))).toLocaleString()} DA</td>
                                    <td className="px-6 md:px-10 py-6 md:py-8 text-center">
                                        <div className="flex justify-center gap-2 md:gap-4">
                                            <button 
                                                onClick={() => {setNewPayment({...newPayment, client: client.id}); setShowPaymentModal(true);}} 
                                                disabled={(parseFloat(client.total_debt) - parseFloat(client.total_paid)) <= 0}
                                                className={`p-3 md:p-4 rounded-xl md:rounded-2xl shadow-xl transition-all ${
                                                    (parseFloat(client.total_debt) - parseFloat(client.total_paid)) <= 0 
                                                    ? 'bg-slate-100 text-slate-300 cursor-not-allowed' 
                                                    : 'bg-emerald-600 text-white hover:scale-105 shadow-emerald-200'
                                                }`}
                                                title={(parseFloat(client.total_debt) - parseFloat(client.total_paid)) <= 0 ? "Aucune dette à encaisser" : "Encaisser un paiement"}
                                            >
                                                <DollarSign size={20}/>
                                            </button>
                                            <button 
                                                onClick={() => handleDeleteClient(client.id)}
                                                className="p-3 md:p-4 bg-rose-50 text-rose-600 rounded-xl md:rounded-2xl hover:bg-rose-600 hover:text-white transition-all shadow-xl shadow-rose-100"
                                            >
                                                <Trash2 size={20}/>
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </motion.div>
        )}
        </AnimatePresence>
      </div>

      <AnimatePresence>
        {showOrderModal && (
            <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-8 bg-slate-900/60 backdrop-blur-md">
                <motion.div initial={{ scale: 0.9, y: 20 }} animate={{ scale: 1, y: 0 }} className="bg-white w-full max-w-3xl rounded-[2.5rem] md:rounded-[3.5rem] p-6 md:p-12 shadow-2xl relative overflow-y-auto max-h-[95vh]">
                    <button onClick={() => { setShowOrderModal(false); setWizardStep(1); }} className="absolute top-6 right-6 md:top-10 md:right-10 p-2 hover:bg-slate-100 rounded-full text-slate-400"><X/></button>
                    {wizardStep === 1 ? (
                        <div className="text-center py-4 md:py-8">
                            <h2 className="text-xl md:text-3xl font-black mb-6 md:mb-8 uppercase tracking-tighter">Client de la commande ?</h2>
                            <form onSubmit={handleClientWizard} className="relative">
                                <input autoFocus type="text" placeholder="Nom du client..." className="w-full p-6 md:p-8 bg-slate-100 border-none rounded-[1.5rem] md:rounded-[2.5rem] text-lg md:text-2xl font-bold text-center outline-none focus:ring-4 ring-emerald-500/10" value={clientSearchQuery} onChange={(e: any) => setClientSearchQuery(e.target.value)} />
                                {clientSearchQuery.length > 1 && (
                                    <div className="absolute top-full left-0 right-0 mt-4 bg-white border border-slate-200 rounded-[1.5rem] md:rounded-[2rem] shadow-2xl z-[130] overflow-hidden max-h-60 overflow-y-auto">
                                        {(clients as any[]).filter((c: any) => c.name.toLowerCase().includes(clientSearchQuery.toLowerCase())).map((c: any) => (
                                            <button key={c.id} type="button" onClick={() => { setNewOrder({...newOrder, client: c.id}); setWizardStep(2); }} className="w-full p-4 md:p-6 text-left hover:bg-emerald-50 font-black border-b border-slate-50 flex justify-between items-center group"><span className="text-sm md:text-base">{c.name}</span><span className="text-[8px] md:text-[10px] uppercase text-emerald-600 bg-emerald-50 px-2 md:px-3 py-1 rounded-full">Existant</span></button>
                                        ))}
                                        <button type="button" onClick={() => { setNewClient({...newClient, name: clientSearchQuery}); setShowClientModal(true); }} className="w-full p-4 md:p-6 text-left bg-slate-900 text-white font-black flex justify-between items-center"><span className="text-sm md:text-base">Créer "{clientSearchQuery}"</span><span className="text-[8px] md:text-[10px] uppercase text-slate-400 tracking-widest">Nouveau</span></button>
                                    </div>
                                )}
                                <button type="submit" className="mt-6 md:mt-8 px-8 md:px-12 py-4 md:py-5 bg-emerald-600 text-white font-black rounded-xl md:rounded-2xl shadow-xl text-sm md:text-base">Continuer</button>
                            </form>
                        </div>
                    ) : (
                        <form onSubmit={handleFinalizeOrder as any} className="space-y-6 md:space-y-8">
                            <div className="flex items-start justify-between border-b pb-4 md:pb-6"><div><h3 className="text-sm md:text-xl font-black uppercase tracking-widest text-slate-400">Client</h3><p className="text-lg md:text-2xl font-black text-slate-800 mt-1 md:mt-2">{(clients as any[]).find((c: any) => c.id == newOrder.client)?.name}</p></div><button type="button" onClick={() => setWizardStep(1)} className="px-3 md:px-4 py-1.5 md:py-2 border border-slate-200 rounded-lg md:rounded-xl text-[8px] md:text-[10px] font-black uppercase text-slate-400 hover:text-emerald-600 transition-all">Changer</button></div>
                            <div className="space-y-2">
                                <p className="text-[10px] font-black uppercase text-slate-400 ml-1">Date de livraison prévue</p>
                                <input type="date" className="w-full p-4 bg-slate-50 border-none rounded-xl md:rounded-2xl font-black text-sm md:text-base" value={newOrder.expected_delivery} min={new Date().toISOString().split('T')[0]} onChange={(e: any) => setNewOrder({...newOrder, expected_delivery: e.target.value})} required />
                            </div>
                            <div className="space-y-4 max-h-48 md:max-h-60 overflow-y-auto pr-2">
                                {newOrder.items.map((item: any, idx: number) => (
                                    <div key={idx} className="grid grid-cols-12 gap-2 md:gap-3 items-center">
                                        <select className="col-span-12 md:col-span-7 p-3 md:p-4 bg-slate-50 rounded-xl md:rounded-2xl font-black text-xs md:text-base" value={item.product} onChange={(e: any) => {
                                            const items = [...newOrder.items]; const prod = (products as any[]).find((p: any) => p.id == e.target.value);
                                            items[idx].product = e.target.value; items[idx].price_at_sale = prod ? prod.unit_price : 0;
                                            setNewOrder({...newOrder, items});
                                        }} required><option value="">Produit...</option>{(products as any[]).map((p: any) => <option key={p.id} value={p.id}>{p.name} ({p.unit_price} DA)</option>)}</select>
                                        <div className="col-span-9 md:col-span-3 flex items-center bg-slate-50 rounded-xl md:rounded-2xl overflow-hidden">
                                            <input type="number" placeholder="Qté" className="w-full p-3 md:p-4 bg-transparent border-none font-black text-center text-xs md:text-base" onFocus={(e: any) => e.target.select()} value={item.quantity} onChange={(e: any) => { const items = [...newOrder.items]; items[idx].quantity = e.target.value; setNewOrder({...newOrder, items}); }} required />
                                        </div>
                                        <button type="button" onClick={() => {
                                            if (newOrder.items.length > 1) {
                                                const items = newOrder.items.filter((_, i) => i !== idx);
                                                setNewOrder({...newOrder, items});
                                            } else {
                                                showMsg("La commande doit contenir au moins un produit", "info");
                                            }
                                        }} className="col-span-3 md:col-span-2 p-3 md:p-4 bg-rose-50 text-rose-600 rounded-xl md:rounded-2xl hover:bg-rose-600 hover:text-white transition-all flex items-center justify-center">
                                            <Trash2 size={16}/>
                                        </button>
                                    </div>
                                ))}
                                <button type="button" onClick={() => setNewOrder({...newOrder, items: [...newOrder.items, { product: '', quantity: 1, price_at_sale: 0 }]})} className="text-[8px] md:text-[10px] font-black text-emerald-600 uppercase tracking-widest">+ Ajouter un produit</button>
                            </div>
                            <div className="bg-slate-900 text-white p-6 md:p-8 rounded-2xl md:rounded-3xl flex flex-col sm:flex-row justify-between items-center shadow-xl gap-4">
                                <div className="text-center sm:text-left"><p className="text-[8px] md:text-[10px] font-black uppercase text-white/40 mb-1">Total HT</p><p className="text-lg md:text-xl font-bold">{calculateWizardTotal().ht.toLocaleString()} DA</p></div>
                                <div className="text-center sm:text-right"><p className="text-[8px] md:text-[10px] font-black uppercase text-orange-400 mb-1 text-sm md:text-lg">Total TTC</p><p className="text-2xl md:text-3xl font-black text-orange-500">{calculateWizardTotal().ttc.toLocaleString()} DA</p></div>
                            </div>
                            <button type="submit" className="w-full py-4 md:py-6 bg-emerald-600 text-white font-black rounded-xl md:rounded-[2rem] shadow-2xl text-base md:text-xl hover:scale-[1.02] transition-all flex items-center justify-center gap-2 md:gap-3"><Save size={20}/> Lancer la Commande</button>
                        </form>
                    )}
                </motion.div>
            </div>
        )}

        {showClientModal && (
            <div className="fixed inset-0 z-[140] flex items-center justify-center p-8 bg-slate-900/60 backdrop-blur-md">
                <motion.div initial={{ scale: 0.9 }} animate={{ scale: 1 }} className="bg-white w-full max-w-2xl rounded-[3rem] p-12 shadow-2xl relative">
                    <button onClick={() => setShowClientModal(false)} className="absolute top-10 right-10 p-2 hover:bg-slate-100 rounded-full text-slate-400"><X/></button>
                    <h2 className="text-3xl font-black mb-10 text-center uppercase tracking-tighter">Enregistrer Client</h2>
                    <form onSubmit={handleAddClient} className="grid grid-cols-2 gap-6">
                        <input className="col-span-2 p-5 bg-slate-50 rounded-2xl font-bold" type="text" placeholder="Nom Complet" value={newClient.name} onChange={(e: any) => setNewClient({...newClient, name: e.target.value})} required />
                        <input className="p-5 bg-slate-50 rounded-2xl font-bold" type="text" placeholder="Téléphone" value={newClient.phone} onChange={(e: any) => setNewClient({...newClient, phone: e.target.value})} required />
                        <select className="p-5 bg-slate-50 rounded-2xl font-bold" value={newClient.domain} onChange={(e: any) => setNewClient({...newClient, domain: e.target.value})}><option value="SOCIETE">Société</option><option value="PARFUMERIE">Parfumerie</option></select>
                        <input className="col-span-2 p-5 bg-slate-50 rounded-2xl font-bold" type="text" placeholder="Adresse" value={newClient.address} onChange={(e: any) => setNewClient({...newClient, address: e.target.value})} required />
                        <button type="submit" className="col-span-2 py-5 bg-slate-900 text-white font-black rounded-2xl shadow-xl hover:bg-emerald-600 transition-all uppercase tracking-widest text-xs">Valider</button>
                    </form>
                </motion.div>
            </div>
        )}
        
        {showPaymentModal && (
            <div className="fixed inset-0 z-[140] flex items-center justify-center p-8 bg-slate-900/60 backdrop-blur-md">
                <motion.div initial={{ scale: 0.9 }} animate={{ scale: 1 }} className="bg-white w-full max-w-md rounded-[3rem] p-12 shadow-2xl relative">
                    <button onClick={() => setShowPaymentModal(false)} className="absolute top-10 right-10 p-2 hover:bg-slate-100 rounded-full text-slate-400"><X/></button>
                    <h2 className="text-3xl font-black mb-10 text-center uppercase tracking-tighter">Encaisser</h2>
                    <form onSubmit={handleAddPayment} className="space-y-6">
                        <div className="p-4 bg-emerald-50 rounded-2xl border border-emerald-100">
                            <p className="text-[10px] font-black uppercase text-emerald-600 mb-1">Client</p>
                            <p className="font-black text-slate-800">{(clients as any[]).find((c: any) => c.id === newPayment.client)?.name}</p>
                        </div>
                        <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold text-2xl text-center" type="number" onFocus={(e: any) => e.target.select()} value={newPayment.amount} onChange={(e: any) => setNewPayment({...newPayment, amount: e.target.value})} required />
                        <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold" type="text" placeholder="Note" value={newPayment.note} onChange={(e: any) => setNewPayment({...newPayment, note: e.target.value})} />
                        <button type="submit" className="w-full py-5 bg-emerald-600 text-white font-black rounded-2xl shadow-xl hover:bg-emerald-700 transition-all uppercase tracking-widest text-xs">Valider</button>
                    </form>
                </motion.div>
            </div>
        )}

        {showStockUpdateModal && selectedMaterial && (
            <div className="fixed inset-0 z-[140] flex items-center justify-center p-8 bg-slate-900/60 backdrop-blur-md">
                <motion.div initial={{ scale: 0.9 }} animate={{ scale: 1 }} className="bg-white w-full max-w-md rounded-[3rem] p-12 shadow-2xl relative">
                    <button onClick={() => setShowStockUpdateModal(false)} className="absolute top-10 right-10 p-2 hover:bg-slate-100 rounded-full text-slate-400"><X/></button>
                    <h2 className="text-3xl font-black mb-10 text-center uppercase tracking-tighter">Mise à jour Stock</h2>
                    <form onSubmit={handleUpdateStock} className="space-y-6">
                        <div className="p-4 bg-slate-50 rounded-2xl">
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1">Matière</p>
                            <p className="font-black text-slate-800">{(selectedMaterial as any).name}</p>
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-2 ml-1">Ajouter ({(selectedMaterial as any).unit})</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold text-2xl text-center" type="number" step="0.01" onFocus={(e: any) => e.target.select()} value={stockAddAmount} onChange={(e: any) => setStockAddAddAmount(e.target.value)} required />
                        </div>
                        <button type="submit" className="w-full py-5 bg-emerald-600 text-white font-black rounded-2xl shadow-xl hover:bg-emerald-700 transition-all uppercase tracking-widest text-xs">Confirmer</button>
                    </form>
                </motion.div>
            </div>
        )}

        {showProductStockModal && selectedProduct && (
            <div className="fixed inset-0 z-[140] flex items-center justify-center p-8 bg-slate-900/60 backdrop-blur-md">
                <motion.div initial={{ scale: 0.9 }} animate={{ scale: 1 }} className="bg-white w-full max-w-md rounded-[3rem] p-12 shadow-2xl relative">
                    <button onClick={() => setShowProductStockModal(false)} className="absolute top-10 right-10 p-2 hover:bg-slate-100 rounded-full text-slate-400"><X/></button>
                    <h2 className="text-3xl font-black mb-10 text-center uppercase tracking-tighter">Entrée Stock</h2>
                    <form onSubmit={handleUpdateProductStock} className="space-y-6">
                        <div className="p-4 bg-orange-50 rounded-2xl border border-orange-100">
                            <p className="text-[10px] font-black uppercase text-orange-600 mb-1">Produit Fini</p>
                            <p className="font-black text-slate-800">{(selectedProduct as any).name}</p>
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-2 ml-1">Quantité ({(selectedProduct as any).unit})</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold text-2xl text-center text-orange-600" type="number" step="0.01" onFocus={(e: any) => e.target.select()} value={stockAddAmount} onChange={(e: any) => setStockAddAddAmount(e.target.value)} required />
                        </div>
                        <button type="submit" className="w-full py-5 bg-orange-500 text-white font-black rounded-2xl shadow-xl hover:bg-orange-600 transition-all uppercase tracking-widest text-xs">Valider l'entrée</button>
                    </form>
                </motion.div>
            </div>
        )}

        {showProductModal && (
            <div className="fixed inset-0 z-[140] flex items-center justify-center p-8 bg-slate-900/60 backdrop-blur-md">
                <motion.div initial={{ scale: 0.9 }} animate={{ scale: 1 }} className="bg-white w-full max-w-2xl rounded-[3rem] p-12 shadow-2xl relative overflow-y-auto max-h-[90vh]">
                    <button onClick={() => setShowProductModal(false)} className="absolute top-10 right-10 p-2 hover:bg-slate-100 rounded-full text-slate-400"><X/></button>
                    <h2 className="text-3xl font-black mb-10 text-center uppercase tracking-tighter">Nouveau Produit</h2>
                    <form onSubmit={handleAddProduct} className="grid grid-cols-2 gap-6">
                        <div className="col-span-2">
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Nom</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold" type="text" value={newProduct.name} onChange={(e: any) => handleNameChange(e)} required />
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Unité</p>
                            <select className="w-full p-5 bg-slate-50 rounded-2xl font-bold" value={newProduct.unit} onChange={(e: any) => setNewProduct({...newProduct, unit: e.target.value})} required>
                                <option value="UNIT">Unités</option>
                                <option value="KG">Kilogrammes</option>
                                <option value="L">Litres</option>
                            </select>
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Stock Initial</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold" type="number" onFocus={(e: any) => e.target.select()} value={newProduct.quantity} onChange={(e: any) => setNewProduct({...newProduct, quantity: e.target.value})} />
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Prix Achat (DA)</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold" type="number" onFocus={(e: any) => e.target.select()} value={newProduct.purchase_price} onChange={(e: any) => setNewProduct({...newProduct, purchase_price: e.target.value})} required />
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Prix Vente (DA)</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold" type="number" onFocus={(e: any) => e.target.select()} value={newProduct.unit_price} onChange={(e: any) => setNewProduct({...newProduct, unit_price: e.target.value})} required />
                        </div>
                        <div className="col-span-2">
                            <label className="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed border-slate-300 rounded-2xl cursor-pointer bg-slate-50 hover:bg-emerald-50 transition-all">
                                <div className="flex flex-col items-center justify-center pt-5 pb-6">
                                    <Camera className="w-8 h-8 mb-2 text-slate-400" />
                                    <p className="text-sm text-slate-500 font-bold">{newProduct.image ? (newProduct.image as any).name : "Importer Photo"}</p>
                                </div>
                                <input type="file" className="hidden" accept="image/*" onChange={(e: any) => setNewProduct({...newProduct, image: e.target.files[0]})} />
                            </label>
                        </div>
                        <div className="col-span-2">
                            <textarea className="w-full p-5 bg-slate-50 rounded-2xl font-bold text-sm" rows={4} value={newProduct.description} onChange={(e: any) => setNewProduct({...newProduct, description: e.target.value})} />
                        </div>
                        <button type="submit" className="col-span-2 py-5 bg-emerald-600 text-white font-black rounded-2xl shadow-xl hover:bg-emerald-700 transition-all">Créer le Produit</button>
                    </form>
                </motion.div>
            </div>
        )}

        {showEditProductModal && editProductData && (
            <div className="fixed inset-0 z-[140] flex items-center justify-center p-8 bg-slate-900/60 backdrop-blur-md">
                <motion.div initial={{ scale: 0.9 }} animate={{ scale: 1 }} className="bg-white w-full max-w-2xl rounded-[3rem] p-12 shadow-2xl relative overflow-y-auto max-h-[90vh]">
                    <button onClick={() => setShowEditProductModal(false)} className="absolute top-10 right-10 p-2 hover:bg-slate-100 rounded-full text-slate-400"><X/></button>
                    <h2 className="text-3xl font-black mb-10 text-center uppercase tracking-tighter">Modifier Produit</h2>
                    <form onSubmit={handleUpdateProduct} className="grid grid-cols-2 gap-6">
                        <div className="col-span-2">
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Nom</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold" type="text" value={editProductData.name} onChange={(e: any) => setEditProductData({...editProductData, name: e.target.value})} required />
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Unité</p>
                            <select className="w-full p-5 bg-slate-50 rounded-2xl font-bold" value={editProductData.unit} onChange={(e: any) => setEditProductData({...editProductData, unit: e.target.value})} required>
                                <option value="UNIT">Unités</option>
                                <option value="KG">Kilogrammes</option>
                                <option value="L">Litres</option>
                            </select>
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Stock Actuel</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold" type="number" onFocus={(e: any) => e.target.select()} value={editProductData.quantity} onChange={(e: any) => setEditProductData({...editProductData, quantity: e.target.value})} />
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Prix Achat (DA)</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold" type="number" onFocus={(e: any) => e.target.select()} value={editProductData.purchase_price} onChange={(e: any) => setEditProductData({...editProductData, purchase_price: e.target.value})} required />
                        </div>
                        <div>
                            <p className="text-[10px] font-black uppercase text-slate-400 mb-1 ml-1">Prix Vente (DA)</p>
                            <input className="w-full p-5 bg-slate-50 rounded-2xl font-bold" type="number" onFocus={(e: any) => e.target.select()} value={editProductData.unit_price} onChange={(e: any) => setEditProductData({...editProductData, unit_price: e.target.value})} required />
                        </div>
                        <div className="col-span-2">
                            <label className="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed border-slate-300 rounded-2xl cursor-pointer bg-slate-50 hover:bg-emerald-50 transition-all">
                                <div className="flex flex-col items-center justify-center pt-5 pb-6">
                                    <Camera className="w-8 h-8 mb-2 text-slate-400" />
                                    <p className="text-sm text-slate-500 font-bold">{(editProductData.image as any) instanceof File ? (editProductData.image as any).name : "Changer Photo"}</p>
                                </div>
                                <input type="file" className="hidden" accept="image/*" onChange={(e: any) => setEditProductData({...editProductData, image: e.target.files[0]})} />
                            </label>
                        </div>
                        <div className="col-span-2">
                            <textarea className="w-full p-5 bg-slate-50 rounded-2xl font-bold text-sm" rows={4} value={editProductData.description} onChange={(e: any) => setEditProductData({...editProductData, description: e.target.value})} />
                        </div>
                        <button type="submit" className="col-span-2 py-5 bg-slate-900 text-white font-black rounded-2xl shadow-xl hover:bg-emerald-600 transition-all">Sauvegarder</button>
                    </form>
                </motion.div>
            </div>
        )}
      </AnimatePresence>

      <ModernNotification notification={notification} onClose={() => setNotification(null)} />
    </main>
  )
}

interface ModernNotificationProps {
  notification: {
    message: string;
    type: 'error' | 'success' | 'info' | 'confirm';
    onConfirm?: () => void;
  } | null;
  onClose: () => void;
}

function ModernNotification({ notification, onClose }: ModernNotificationProps) {
  if (!notification) return null;

  const config = {
    success: { icon: <CheckCircle2 size={32}/>, color: 'bg-emerald-600', shadow: 'shadow-emerald-200' },
    error: { icon: <AlertCircle size={32}/>, color: 'bg-rose-600', shadow: 'shadow-rose-200' },
    confirm: { icon: <AlertCircle size={32}/>, color: 'bg-orange-500', shadow: 'shadow-orange-200' },
    info: { icon: <Info size={32}/>, color: 'bg-slate-900', shadow: 'shadow-slate-200' }
  }

  const { icon, color, shadow } = config[notification.type as keyof typeof config];

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center pointer-events-none p-6">
      <motion.div 
        initial={{ opacity: 0, scale: 0.8, y: 40 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.8, y: 20 }}
        className={`pointer-events-auto max-w-lg w-full ${color} text-white p-8 rounded-[2.5rem] shadow-2xl ${shadow} flex flex-col items-center text-center gap-6 border-4 border-white/20 backdrop-blur-lg`}
      >
        <div className="w-20 h-20 bg-white/20 rounded-3xl flex items-center justify-center animate-pulse">
          {icon}
        </div>
        <div className="space-y-2">
          <h4 className="text-xl font-black uppercase tracking-widest opacity-60">
            {notification.type === 'confirm' ? 'Confirmation' : notification.type === 'error' ? 'Attention' : 'Notification'}
          </h4>
          <p className="text-xl font-bold leading-relaxed whitespace-pre-wrap">
            {notification.message}
          </p>
        </div>
        
        {notification.type === 'confirm' ? (
          <div className="flex gap-4 w-full mt-2">
            <button 
              onClick={() => { notification.onConfirm?.(); onClose(); }}
              className="flex-1 py-4 bg-white text-orange-600 font-black rounded-2xl hover:bg-orange-50 transition-all active:scale-95 text-sm uppercase tracking-widest"
            >
              Oui, Forcer
            </button>
            <button 
              onClick={onClose}
              className="flex-1 py-4 bg-orange-700 text-white font-black rounded-2xl hover:bg-orange-800 transition-all active:scale-95 text-sm uppercase tracking-widest"
            >
              Annuler
            </button>
          </div>
        ) : (
          <button 
            onClick={onClose}
            className="mt-2 px-8 py-3 bg-white text-slate-900 font-black rounded-xl hover:bg-slate-100 transition-all active:scale-95 text-xs uppercase tracking-widest"
          >
            Compris
          </button>
        )}
      </motion.div>
    </div>
  )
}

interface TabButtonProps {
    active: boolean;
    onClick: () => void;
    label: string;
    icon: React.ReactNode;
}

function TabButton({ active, onClick, label, icon }: TabButtonProps) {
    return (
        <button onClick={onClick} className={`px-4 md:px-10 py-3 md:py-5 rounded-xl md:rounded-[2rem] font-black text-xs md:text-sm flex items-center gap-2 md:gap-4 transition-all whitespace-nowrap active:scale-95 ${active ? 'bg-slate-900 text-white shadow-[0_10px_20px_-5px_rgba(0,0,0,0.2)] md:shadow-[0_20px_40px_-10px_rgba(0,0,0,0.3)] scale-105' : 'bg-white text-slate-400 hover:bg-emerald-50 hover:text-emerald-600 border border-slate-100'}`}>
            {icon} {label}
        </button>
    )
}

interface TabButtonProps {
    active: boolean;
    onClick: () => void;
    label: string;
    icon: React.ReactNode;
}

function TabButton({ active, onClick, label, icon }: TabButtonProps) {
    return (
        <button onClick={onClick} className={`px-4 md:px-10 py-3 md:py-5 rounded-xl md:rounded-[2rem] font-black text-xs md:text-sm flex items-center gap-2 md:gap-4 transition-all whitespace-nowrap active:scale-95 ${active ? 'bg-slate-900 text-white shadow-[0_10px_20px_-5px_rgba(0,0,0,0.2)] md:shadow-[0_20px_40px_-10px_rgba(0,0,0,0.3)] scale-105' : 'bg-white text-slate-400 hover:bg-emerald-50 hover:text-emerald-600 border border-slate-100'}`}>
            {icon} {label}
        </button>
    )
}

interface InsightCardProps {
    label: string;
    value: string | number;
    unit: string;
    status: 'danger' | 'success' | 'info';
    icon: React.ReactElement<any>;
    desc: string;
}

function InsightCard({ label, value, unit, status, icon, desc }: InsightCardProps) {
  const colors = { 
    danger: 'text-rose-600 bg-rose-50 border-rose-100', 
    success: 'text-emerald-600 bg-emerald-50 border-emerald-100', 
    info: 'text-orange-600 bg-orange-50 border-orange-100' 
  }
  return (
    <div className={`bg-white p-6 md:p-10 rounded-[2rem] md:rounded-[3rem] border ${colors[status as keyof typeof colors] || colors.info} shadow-xl relative overflow-hidden group hover:scale-[1.02] md:hover:scale-[1.05] transition-all duration-500`}>
      <div className={`w-12 h-12 md:w-16 md:h-16 ${colors[status as keyof typeof colors].split(' ')[1]} rounded-xl md:rounded-[1.5rem] flex items-center justify-center mb-4 md:mb-6`}>{React.cloneElement(icon as React.ReactElement<any>, { size: 24 })}</div>
      <p className="text-slate-400 text-[9px] md:text-[11px] font-black uppercase mb-1 md:mb-2 tracking-[0.1em]">{label}</p>
      <div className={`text-2xl md:text-4xl font-black tracking-tight ${(colors[status as keyof typeof colors] || colors.info).split(' ')[0]}`}>{value} <small className="text-[10px] md:text-sm font-black opacity-30 uppercase">{unit}</small></div>
      <p className="mt-4 md:mt-6 text-[8px] md:text-[10px] font-bold text-slate-400 uppercase tracking-widest">{desc}</p>
      <div className="absolute top-0 right-0 p-2 md:p-4 opacity-5 group-hover:opacity-20 transition-opacity">
        {React.cloneElement(icon as React.ReactElement<any>, { size: 80 })}
      </div>
    </div>
  )
}
